version: '2'

services:

  gateway-config:
    image: nebraltd/hm-config:arm64-a198b83
    depends_on:
      - dbus-session
      - helium-miner
      - diagnostics
    environment:
      - FIRMWARE_VERSION=v1.3.0
      - FIRMWARE_SHORT_HASH=c2dd87a
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
    restart: on-failure
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - miner-storage:/var/data
      - dbus:/session/dbus
      - nebra:/var/nebra
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.kernel-modules: 1
      io.balena.features.dbus: 1
    stop_signal: SIGINT

  packet-forwarder:
    image: nebraltd/hm-pktfwd:5c3c90a
    restart: always
    privileged: true
    volumes:
      - pktfwdr:/var/pktfwd
      - nebra:/var/nebra
    environment:
      - FIRMWARE_VERSION=v1.3.0
      - FIRMWARE_SHORT_HASH=c2dd87a
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.procfs: 1

  helium-miner:
    image: quay.io/team-helium/miner:gateway-latest
    environment:
      - REGION_OVERRIDE=EU868
      - GW_REGION=EU868
      - GW_KEYPAIR=ecc://i2c-1
      - GW_LISTEN=0.0.0.0:1680
      - GW_API=0.0.0.0:4467
    ports:
      - "1680:1680/udp"
      - "4467:4467/tcp"
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/i2c-1:/dev/i2c-1
    restart: unless-stopped
    volumes:
      - pktfwdr:/var/pktfwd
      - miner-storage:/var/data
      - nebra:/var/nebra

  diagnostics:
    image: nebraltd/hm-diag:arm64-6d56740
    depends_on:
      - dbus-session
    environment:
      - FIRMWARE_VERSION=v1.3.0
      - FIRMWARE_SHORT_HASH=c2dd87a
      - DIAGNOSTICS_VERSION=6d56740
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - CONFIG_VERSION=a198b83
      - PKTFWD_VERSION=5c3c90a
    volumes:
      - pktfwdr:/var/pktfwd
      - miner-storage:/var/data
      - watchdog-log:/var/watchdog
      - nebra:/var/nebra
    ports:
      - "80:80"
    cap_add:
      - SYS_RAWIO
    restart: always
    privileged: true
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.procfs: 1
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-api: 1

  dbus-session:
    image: balenablocks/dbus:rpi-0.0.2
    restart: always
    volumes:
      - dbus:/session/dbus
    environment:
      - DBUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
      - FIRMWARE_VERSION=v1.3.0
      - FIRMWARE_SHORT_HASH=c2dd87a

volumes:
  miner-storage:
  pktfwdr:
  dbus:
  nebra:
  watchdog-log: